### ISSUE TITLE
Esphome Update

### ISSUE THREAD

**Issue by Trunks1982** [PedroKTFC/esphome-tesla-ble#21]
Hier tauchen Fehler auf seid dem ich gerade mein Esphome upgedatet habe.

![Image](https://github.com/user-attachments/assets/4e727dd7-e695-4d44-a004-f8ca5b944b2e)

**Comment by PedroKTFC** [comment]
No idea what's happening. Have you cleaned your build files? I've also released a new version this evening to the default branch so rebuilding against that might work (although github's caching may delay a build against that release). otherwise, what does your yaml look like?

**Comment by stieler-it** [comment]
I wanted to try the fork today and seem to get the same error message. I tried cleaning the build files but it didn't fix it.
ESPHome 2025.5.1 and the config basically this: https://github.com/PedroKTFC/esphome-tesla-ble/blob/newteslalib/tesla-ble.example.yml

**Comment by PedroKTFC** [comment]
At the time of writing they are identical.

**Comment by Trunks1982** [comment]
Ich nutze ja schon die dev version von vor zwei wochen oder so. Wollte nur updaten und dann kam die Fehlermeldung. Habe an meiner yaml nur die uodateinterval abfragen eingefügt sonnst ist alles gleich geblieben. Bis jetzt funktioniert es jedenfalls noch nicht. Immer noch gleiche Fehlermeldung.

**Comment by PedroKTFC** [comment]
You should be able to build using the main branch. What's your yaml?

**Comment by Trunks1982** [comment]
> You should be able to build using the main branch. What's your yaml?



Wie gesagt mit dev hats vorher immer funktioniert. Jetzt hab ich mal das neue hinzugefügt gleiche Problem.

substitutions:
  name: tesla-ble-modely
  friendly_name: Tesla BLE Model Y
  charging_amps_max: "16"
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB

#external_components:   # Use this block instead of the one above if you want to use the development branch
#  - source:
#      type: git
#      url: https://github.com/PedroKTFC/esphome-tesla-ble.git
#      ref: dev
#    refresh: 0s


#packages:
#  remote_package_files:
#    url: https://github.com/PedroKTFC/esphome-tesla-ble.git
#    files: [tesla-ble-esp32-generic.dashboard.yml] 
#    ref: dev  # optional
#    refresh: 0s  # optional

external_components:
  source: github://PedroKTFC/esphome-tesla-ble

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address


esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

web_server:
  port: 80
  version: 3

api:
  encryption:
    key: !secret api_encryption_key

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: 
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  charge_state:
    name: "Charge level"
    unit_of_measurement: "%"
  battery_range:
    name: "Reichweite"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)    

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 10s
    entity_category: diagnostic
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.156
    gateway: 192.168.0.1
    subnet: 255.255.255.0

**Comment by Trunks1982** [comment]
Danke hier mit ging es jetzt:


ubstitutions:
  name: tesla-ble-modely
  friendly_name: Tesla BLE Model Y
  charging_amps_max: "16"
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB

external_components:
  - source:
      type: git
      url: https://github.com/PedroKTFC/esphome-tesla-ble
    refresh: 0s
    components: [tesla_ble_vehicle] #, tesla_ble_listener]

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml
#  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git


web_server:
  port: 80
  version: 3

api:
  encryption:
    key: !secret api_encryption_key

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: 
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  charge_state:
    name: "Charge level"
    unit_of_measurement: "%"
  battery_range:
    name: "Reichweite"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)    

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 10s
    entity_category: diagnostic
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.156
    gateway: 192.168.0.1
    subnet: 255.255.255.0

**Comment by lukej0** [comment]
> > As I understand, and that's how it worked for me, you have to define, which library to load.
> > 
> > So you have to add to your config:
> > 
> > ```
> > esphome:
> >   libraries:
> >     - https://github.com/pedroktfc/tesla-ble.git
> > ```
> > 
> > Have in mind, if you want to try the dev-branch you should consider to also use the dev version of the library. To do so, just add #dev after .git But for now the main branch is pretty much the same version as the dev version for my understanding.
> 
> Can you be more specific in where I should add this? I'm also getting compilation issues very similar to the above.  I am very new to esphome.  What config file do l add this to exactly?

It's in the main config of your esp device. When you are in home assistant, head to the esphome addon, and click edit on your device
![Screenshot_20250603-043913~2.png](https://github.com/user-attachments/assets/edc0eea5-7758-4179-832e-db15fcc3db47)

Then add the libraries entry under the esphome section (like in line 6 in the following screenshot)
![Screenshot_20250603-043943.png](https://github.com/user-attachments/assets/facded90-5542-4e86-8374-0e3521bdbb84)

**Comment by lukej0** [comment]
I am also using the m5stack nanoc6.
This is my yaml. Please take note, that it references to the dev branch. And if you like to be accessible via static IP you could uncomment (delete the "#") the part with manual_ip and the subentries and fill them with your data.

```
esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev
  
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
    #board_build.f_cpu: 160000000L
    #board_build.f_flash: 80000000L
    #board_build.flash_size: 4MB
    #build_flags: "-DBOARD_HAS_PSRAM"
    #board_build.arduino.memory_type: qio_opi

substitutions:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  name: tesla-ble
  friendly_name: "Tesla BLE v4"
  charging_amps_max: "16"
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

esp32:
  framework:
    type: esp-idf
    version: 5.2.1
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Board specific entities
light:
  - platform: status_led
    name: "Status LED"
    entity_category: diagnostic
    pin: GPIO7

  #G20=RGB WS2812
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO20
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    # rmt_channel: 1
    chipset: ws2812
    name: "RGB LED"
    entity_category: diagnostic
    power_supply: rgbpwr

power_supply:
  - id: 'rgbpwr'
    enable_on_boot: true
    pin: GPIO19
    enable_time: 10ms
    keep_on_time: 10ms

#G9=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  #manual_ip:
    #static_ip: xxx
    #gateway: xxx
    #subnet: xxx

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

external_components:
  - source: github://pedroktfc/esphome-tesla-ble@dev
    refresh: 1h 

packages:
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev
  # listener: github://pedroktfc/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

dashboard_import:
  package_import_url: github://pedroktfc/esphome-tesla-ble/tesla-ble-esp31-generic.dashboard.yml@dev

tesla_ble_vehicle:
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
```

**Comment by scottismyname** [comment]
> I am also using the m5stack nanoc6. This is my yaml. Please take note, that it references to the dev branch. And if you like to be accessible via static IP you could uncomment (delete the "#") the part with manual_ip and the subentries and fill them with your data.
> 
> ```
> esphome:
>   name: ${name}
>   name_add_mac_suffix: true
>   friendly_name: ${friendly_name}
>   
>   libraries:
>     - https://github.com/PedroKTFC/tesla-ble.git#dev
>   
>   platformio_options:
>     platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
>     #board_build.f_cpu: 160000000L
>     #board_build.f_flash: 80000000L
>     #board_build.flash_size: 4MB
>     #build_flags: "-DBOARD_HAS_PSRAM"
>     #board_build.arduino.memory_type: qio_opi
> 
> substitutions:
>   board: esp32-c6-devkitm-1
>   variant: esp32c6
>   flash_size: 4MB
>   name: tesla-ble
>   friendly_name: "Tesla BLE v4"
>   charging_amps_max: "16"
>   ble_mac_address: !secret ble_mac_address
>   tesla_vin: !secret tesla_vin
> 
> esp32:
>   framework:
>     type: esp-idf
>     version: 5.2.1
>     sdkconfig_options:
>       CONFIG_OPENTHREAD_ENABLED: n
>       CONFIG_ENABLE_WIFI_STATION: y
>       CONFIG_USE_MINIMAL_MDNS: y
>       CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
> 
> # Board specific entities
> light:
>   - platform: status_led
>     name: "Status LED"
>     entity_category: diagnostic
>     pin: GPIO7
> 
>   #G20=RGB WS2812
>   - platform: esp32_rmt_led_strip
>     rgb_order: GRB
>     pin: GPIO20
>     num_leds: 4
>     # RMT 0 channels will be occupied by IR
>     # rmt_channel: 1
>     chipset: ws2812
>     name: "RGB LED"
>     entity_category: diagnostic
>     power_supply: rgbpwr
> 
> power_supply:
>   - id: 'rgbpwr'
>     enable_on_boot: true
>     pin: GPIO19
>     enable_time: 10ms
>     keep_on_time: 10ms
> 
> #G9=Button
> binary_sensor:
>   - platform: gpio
>     name: Button
>     entity_category: diagnostic
>     pin:
>       number: GPIO9
>       inverted: true
>       mode:
>         input: true
>         pullup: true
>     filters:
>       - delayed_off: 10ms
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: !secret api_encryption_key
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
>   # Optional manual IP
>   #manual_ip:
>     #static_ip: xxx
>     #gateway: xxx
>     #subnet: xxx
> 
> button:
>   - platform: factory_reset
>     name: Restart with Factory Default Settings
> 
> external_components:
>   - source: github://pedroktfc/esphome-tesla-ble@dev
>     refresh: 1h 
> 
> packages:
>   base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
>   device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml@dev
>   client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev
>   # listener: github://pedroktfc/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address
> 
> dashboard_import:
>   package_import_url: github://pedroktfc/esphome-tesla-ble/tesla-ble-esp31-generic.dashboard.yml@dev
> 
> tesla_ble_vehicle:
>   odometer:
>     name: "Odometer"
>     unit_of_measurement: "km"
>     filters:
>       - multiply: 1.60934 # Convert miles to kms
>   battery_range:
>     name: "Range"
>     unit_of_measurement: "km"
>     filters:
>       - multiply: 1.60934 # Convert miles to kms
>   update_interval: 2s # default
>   post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
>   poll_data_period: 60 # Normal period when polling for data when not asleep (s)
>   poll_charging_period: 2 # Period to poll for data when charging (s)
>   ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
> ```

Brilliant, this works for me thanks! My nanoc6 should get here today, but this line confused me, as I don't see that file anywhere.  Is this just not needed since most everything is already in this file?

```
dashboard_import:
  package_import_url: github://pedroktfc/esphome-tesla-ble/tesla-ble-esp31-generic.dashboard.yml@dev
```

**Comment by PedroKTFC** [comment]
I no longer have that line in my yaml.
